### PR TITLE
Visualising data

### PR DESCRIPTION
**Pull request by ashish4321**
#4 Solved

### CODE REVIEW

**Comment by ashish4321** [comment]
@aka-jumba please review the pr

**Review by ambuj-krishna-agrawal — CHANGES_REQUESTED** [review]
You are required to make scatter plots for the train data and test data. Scatter_matrix performs entirely different task.
Use matplotlib scatter function.

**Review by ashish4321 — COMMENTED** [review]
Changed scatter matrix to scatter plot

**Comment by ashish4321** [comment]
@aka-jumba Changed as requested. pls review

**Pull request merged**
